name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/rbcprolabs/epubx.dart
issue_tracker: https://github.com/rbcprolabs/epubx.dart
version: 3.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.3.5
  quiver: ^3.1.0
  xml: ^6.2.2
  image: ^3.2.2
  collection: any

dev_dependencies:
  test: ^1.22.1
  path: ^1.8.0
  pedantic: ^1.11.0
